[package]
name = "core"
version = "0.1.0"
authors = ["Alexandre Frigon <alexandre.frigon.1@gmail.com>"]
edition = "2018"


[dependencies]
serde = { version = "1.0", features = ["derive"] }
math = { git = "https://github.com/roadrunner-craft/math" }


[lib]
name = "core"
path = "../src/lib.rs"
